---
- name: Retry SSH connection for (up to) 5 minutes
  wait_for_connection:
    timeout: 300

- name: Gather minimal facts
  setup:
    gather_subset: min

- name: Install common apps
  package:
    name: "{{ item }}"
    state: present
  loop:
    - bzip2  # this really ought to be installed by default
    - unzip  # because some people apparently still use zip
    - wget   # like `curl` but defaults to downloading to a file rather than STDIN
    - tmux   # like `screen` but better (iTerm2 integration is OMG)
    - htop   # like `top` but prettier!
    - vim    # like `vi` but I know how to use it
    - git    # why use any other form of source control
    - ack    # like `grep` but recursive and avoids uninteresting files by default
    - jq     # for pretty-printing and manipulating JSON and JSON-LD
    - tree   # for drawing filesystem layouts in ASCII

- name: Install extra apps
  package:
    name: "{{ item }}"
    state: present
  loop:
    - pbzip2      # parallel bzip2
    - psmisc      # installs `pstree` and `killall`, among others, for inspecting running processes
    - lsof        # for inspecting open files
    - vnstat      # simple network traffic monitor
    - pv          # shell pipes monitor
    - ncdu        # interactive `du` for triaging filesystem space usage
    - stow        # GNU stow, for symlink-based installation

- name: Install VNC apps
  package:
    name: "{{ item }}"
    state: present
  loop:
    - xfce4
    - xfce4-goodies
    - tightvncserver
    - dbus-x11

- name: Fix systemd's broken pager
  lineinfile:
    path: /etc/profile.d/systemd_pager.sh
    create: yes
    # all the other files in /etc/profile.d have root:root ownership and rw-r--r-- flags
    owner: root
    group: root
    mode: 0644
    line: export SYSTEMD_PAGER=

- name: Fix systemd's broken pager (when sudo'ing)
  # (depends on /etc/profile.d/systemd_pager.sh having already been sourced in the shell session calling sudo)
  lineinfile:
    path: /etc/sudoers
    line: Defaults env_keep += "SYSTEMD_PAGER"

- name: Ensure user is sudoer
  user:
    name: "{{ ansible_user }}"
    groups: sudo
    append: yes

- name: Ensure the primary (SSH) user owns /usr/local
  file:
    path: /usr/local
    recurse: true
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Treat caps-lock like ctrl
  lineinfile:
    path: /etc/default/keyboard
    regexp: ^XKBOPTIONS=
    line: XKBOPTIONS="ctrl:nocaps"

- name: Disable sleeping
  lineinfile:
    path: /etc/systemd/sleep.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - regexp: AllowSuspend=
      line: AllowSuspend=no
    - regexp: AllowHibernation=
      line: AllowHibernation=no

- name: Allow sudo without having to type password
  lineinfile:
    path: /etc/sudoers
    regexp: ^%sudo
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
