---
- name: Gather minimal facts
  setup:
    gather_subset: min

- name: warn for non-CentOS
  debug:
    msg: >
      OS family is not RedHat, it is "{{ ansible_os_family }}".
      These tasks probably won't run properly.
  when: ansible_os_family != "RedHat"

- name: Install epel (Extra Packages for Enterprise Linux)
  package:
    name: epel-release
    state: present

# - name: update to latest repository information
#   command: yum -y update

- name: Install common apps
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - bzip2  # this really ought to be installed by default
    - unzip  # because some people apparently still use zip
    - wget   # like `curl` but defaults to downloading to a file rather than STDIN
    - tmux   # like `screen` but better (iTerm2 integration is OMG)
    - htop   # like `top` but prettier!
    - vim    # like `vi` but I know how to use it
    - git    # why use any other form of source control
    - ack    # like `grep` but recursive and avoids uninteresting files by default
    - jq     # for pretty-printing and manipulating JSON and JSON-LD
    - tree   # for drawing filesystem layouts in ASCII

- name: Install extra apps
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - pbzip2      # parallel bzip2
    - psmisc      # installs `pstree` and `killall`, among others, for inspecting running processes
    - lsof        # for inspecting open files
    - vnstat      # simple network traffic monitor
    - pv          # shell pipes monitor
    - ncdu        # interactive `du` for triaging filesystem space usage
    - python-pip  # for `pip`, which we immediately self-upgrade
    - stow        # GNU stow, for symlink-based installation
    - bind-utils  # for DNS utils like `dig` and `nslookup`

- name: Upgrade pip
  pip:
    name: pip
    state: latest

- name: Install aws CLI tool
  pip:
    name: awscli
    state: latest

- name: Disable SELinux
  lineinfile:
    # CentOS installs /etc/sysconfig/selinux as a symlink to ../selinux/config
    path: /etc/sysconfig/selinux
    regexp: ^SELINUX=
    line: SELINUX=disabled

- name: Fix systemd's broken pager
  lineinfile:
    path: /etc/profile.d/systemd_pager.sh
    create: yes
    # all the other files in /etc/profile.d have root:root ownership and rw-r--r-- flags
    owner: root
    group: root
    mode: 0644
    line: export SYSTEMD_PAGER=

- name:
  # (depends on /etc/profile.d/systemd_pager.sh having already been sourced in the shell session calling sudo)
  lineinfile:
    path: /etc/sudoers
    line: Defaults env_keep += "SYSTEMD_PAGER"

- name: Ensure the primary (SSH) user owns /usr/local
  file:
    path: /usr/local
    recurse: true
    owner: "{{ ansible_ssh_user }}"
    group: "{{ ansible_ssh_user }}"

- name: Set timezone to CT
  timezone:
    name: America/Chicago

- name: Disable mail server
  service:
    name: postfix
    enabled: no
    state: stopped
