---
- name: reload nginx
  service:
    name: nginx
    state: reloaded # presumably via: sudo nginx -s reload

- name: restart logstash
  service:
    name: logstash
    state: restarted

- name: restart kibana
  service:
    name: kibana
    state: restarted
